version: "2"
services:
  app:
    container_name: twitch-bot
    restart: always
    build: .
    command: [/bin/bash]
    ports:
      - "4200:4200"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"